let data = [
    {
        title:"Nike yellow",
        img:"img/amarillo.png",
        collection:"Running collection",
        description:'Uno de los modelos de Nike en color amarillo es el Nike Air Max 720 "Sunrise". Estas zapatillas tienen una parte superior en amarillo brillante y cuentan con detalles en negro y blanco, así como una suela de aire Max de gran tamaño en tonos de amarillo y naranja para una mayor comodidad y amortiguación.',
        price:"2500",
        color:"#D0912B",
    },
    {
        title:"",
        img:"",
        collection:"Running collection",
        description:'',
        price:"2500",
        color:"#7C5995",
    },
    {
        title:"",
        img:"",
        collection:"Running collection",
        description:'',
        price:"2500",
        color:"#53545C",
    },
    {
        title:"",
        img:"",
        collection:"Running collection",
        description:'',
        price:"2500",
        color:"#8D8F98",
    },
    {
        title:"",
        img:"",
        collection:"Running collection",
        description:'',
        price:"2500",
        color:"#5FB9CF",
    },
    {
        title:"",
        img:"",
        collection:"Running collection",
        description:'',
        price:"2500",
        color:"#35615B",
    },
    {
        title:"",
        img:"",
        collection:"Running collection",
        description:'',
        price:"2500",
        color:"#604FC0",
    },
    {
        title:"",
        img:"",
        collection:"Running collection",
        description:'',
        price:"2500",
        color:"#922E30",
    },
    {
        title:"",
        img:"",
        collection:"Running collection",
        description:'',
        price:"2500",
        color:"#7F2E34",
    },
    {
        title:"",
        img:"",
        collection:"Running collection",
        description:'',
        price:"2500",
        color:"#43554C",
    },
    {
        title:"",
        img:"",
        collection:"Running collection",
        description:'',
        price:"2500",
        color:"#0855B0",
    },
    {
        title:"",
        img:"",
        collection:"Running collection",
        description:'',
        price:"2500",
        color:"#457517",
    }
    
]