let data = [
    {
        title:"Nike yellow",
        img:"img/amarillo.png",
        collection:"Running collection",
        description:'Uno de los modelos de Nike en color amarillo es el Nike Air Max 720 "Sunrise". Estas zapatillas tienen una parte superior en amarillo brillante y cuentan con detalles en negro y blanco, así como una suela de aire Max de gran tamaño en tonos de amarillo y naranja para una mayor comodidad y amortiguación.',
        price:"1900",
        color:"#D0912B",
    },
    {
        title:"Nike purple",
        img:"img/azul.png",
        collection:"Running collection",
        description:'Los Nike Air Max 2090 en color morado tienen una parte superior en tejido transpirable y una suela Air Max para una mayor comodidad y amortiguación.',
        price:"1900",
        color:"#7C5995",
    },
    {
        title:"Nike moon",
        img:"img/gris.png",
        collection:"Limited collection",
        description:'Los Nike Air Max 270 React en color gris claro tienen una parte superior de tejido transpirable y una suela Air Max 270 y React para una mayor comodidad y amortiguación.',
        price:"1600",
        color:"#53545C",
    },
    {
        title:"Nike joy",
        img:"img/gris2.png",
        collection:"Limited collection",
        description:'Los Nike Air Max 2090 en color gris claro tienen una parte superior en tejido transpirable y una suela Air Max para una mayor comodidad y amortiguación.',
        price:"1600",
        color:"#8D8F98",
    },
    {
        title:"Nike aqua/black",
        img:"img/lightBlue.png",
        collection:"Limited collection",
        description:'Los Nike Air Max 270 React en color negro con agujetas verde aqua tienen una parte superior de tejido transpirable y una suela Air Max 270 y React para una mayor comodidad y amortiguación.',
        price:"1600",
        color:"#5FB9CF",
    },
    {
        title:"Nike fresh",
        img:"img/menta.png",
        collection:"Limited collection",
        description:'Los Nike Air Max 270 React en color menta con rosa tienen una parte superior de tejido transpirable y una suela Air Max 270 y React para una mayor comodidad y amortiguación.',
        price:"3000",
        color:"#35615B",
    },
    {
        title:"Nike future",
        img:"img/prupura.png",
        collection:"Running collection",
        description:' Los Nike Air Max 270 React en morado y blanco tienen una combinación de colores llamativa y una suela con la tecnología React que proporciona comodidad y amortiguación durante todo el día.',
        price:"3000",
        color:"#604FC0",
    },
    {
        title:"Nike spartan",
        img:"img/rojo.png",
        collection:"Running collection",
        description:'Los Nike Air Force 107 LV8 en color negro y rojo cuentan con un diseño clásico y el icónico logo de la paloma en la parte trasera para un toque adicional de estilo.',
        price:"1900",
        color:"#922E30",
    },
    {
        title:"Nike force",
        img:"img/rojoFuerte.png",
        collection:"Limited collection",
        description:'Los Nike SB Zoom Blazer Mid en color blanco y negro tienen un diseño inspirado en los icónicos Vans, pero con la tecnología Nike Zoom para una mayor comodidad y rendimiento.',
        price:"2400",
        color:"#7F2E34",
    },
    {
        title:"Nike green",
        img:"img/rosa.png",
        collection:"Limited collection",
        description:'Los Nike Air Max 95 en verde oscuro y gris tienen un estilo clásico de los años 90 y una combinación de colores atractiva, con detalles en negro y blanco para un look completo.',
        price:"2700",
        color:"#43554C",
    },
    {
        title:"Nike dark space",
        img:"img/space.png",
        collection:"Limited collection",
        description:'Los Nike React Vision en azul oscuro y verde neón tienen un diseño futurista y una suela con tecnología React para una mayor comodidad y amortiguación.',
        price:"2900",
        color:"#0855B0",
    },
    {
        title:"Nike lemon",
        img:"img/verde.png",
        collection:"Running collection",
        description:'Los Nike Air Zoom Pegasus 38 en verde limón y negro son ideales para correr o caminar, con una suela Air Zoom para una mayor amortiguación y una parte superior transpirable para una comodidad fresca.',
        price:"3000",
        color:"#457517",
    }
    
]